################################################
# ©️ 2023 Contributors to the TeaChimer project #
################################################

import tkinter as tk
import tkinter.ttk as ttk
import tkinter.messagebox as mbox
import pygame

class SoundBoard:
    def __init__(self, master):
        self.master = master
        self.master.title("TeaChimer-pulicver-1.00")
        self.master.attributes("-fullscreen", True)
        self.master.configure(background="white")

        self.notebook = ttk.Notebook(self.master)
        self.notebook.pack(fill=tk.BOTH, expand=True)

        style = ttk.Style()
        style.configure('Custom.TNotebook.Tab', color="red", padding=(30,10), font=('Noto Sans JP', 25))
        style.configure('Custom.TNotebook', background="white")
        self.notebook.configure(style='Custom.TNotebook')

        self.create_page1()
        self.create_page2()
        self.create_page3()
        self.create_page4()
        self.create_page5()
        self.create_page6()
        self.create_page7()
        self.create_page8()
        self.create_page9()
        self.create_page10()

        self.create_navigation_frame()

    def create_page1(self):
        page1 = tk.Frame(self.notebook, background="white")
        self.notebook.add(page1, text="あ行")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page1, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=4, padx=5, pady=5, sticky="nsew")

        page1.grid_rowconfigure(0, weight=0)
        page1.grid_rowconfigure(1, weight=0)
        page1.grid_rowconfigure(2, weight=0)
        page1.grid_rowconfigure(3, weight=0)
        page1.grid_rowconfigure(4, weight=0)
        page1.grid_columnconfigure(0, weight=1)
        page1.grid_columnconfigure(1, weight=1)
        page1.grid_columnconfigure(2, weight=1)
        page1.grid_columnconfigure(3, weight=1)
        page1.grid_columnconfigure(4, weight=1)

    def create_page2(self):
        page2 = tk.Frame(self.notebook, background="white")
        self.notebook.add(page2, text="か行")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page2, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=4, padx=5, pady=5, sticky="nsew")

        page2.grid_rowconfigure(0, weight=0)
        page2.grid_rowconfigure(1, weight=0)
        page2.grid_rowconfigure(2, weight=0)
        page2.grid_rowconfigure(3, weight=0)
        page2.grid_rowconfigure(4, weight=0)
        page2.grid_columnconfigure(0, weight=1)
        page2.grid_columnconfigure(1, weight=1)
        page2.grid_columnconfigure(2, weight=1)
        page2.grid_columnconfigure(3, weight=1)
        page2.grid_columnconfigure(4, weight=1)

    def create_page3(self):
        page3 = tk.Frame(self.notebook, background="white")
        self.notebook.add(page3, text="さ行")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page3, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=4, padx=5, pady=5, sticky="nsew")

        page3.grid_rowconfigure(0, weight=0)
        page3.grid_rowconfigure(1, weight=0)
        page3.grid_rowconfigure(2, weight=0)
        page3.grid_rowconfigure(3, weight=0)
        page3.grid_rowconfigure(4, weight=0)
        page3.grid_columnconfigure(0, weight=1)
        page3.grid_columnconfigure(1, weight=1)
        page3.grid_columnconfigure(2, weight=1)
        page3.grid_columnconfigure(3, weight=1)
        page3.grid_columnconfigure(4, weight=1)

    def create_page4(self):
        page4 = tk.Frame(self.notebook, background="white")
        self.notebook.add(page4, text="た行")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page4, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=4, padx=5, pady=5, sticky="nsew")

        page4.grid_rowconfigure(0, weight=0)
        page4.grid_rowconfigure(1, weight=0)
        page4.grid_rowconfigure(2, weight=0)
        page4.grid_rowconfigure(3, weight=0)
        page4.grid_rowconfigure(4, weight=0)
        page4.grid_columnconfigure(0, weight=1)
        page4.grid_columnconfigure(1, weight=1)
        page4.grid_columnconfigure(2, weight=1)
        page4.grid_columnconfigure(3, weight=1)
        page4.grid_columnconfigure(4, weight=1)

    def create_page5(self):
        page5 = tk.Frame(self.notebook, background="white")
        self.notebook.add(page5, text="な行")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page5, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=4, padx=5, pady=5, sticky="nsew")

        page5.grid_rowconfigure(0, weight=0)
        page5.grid_rowconfigure(1, weight=0)
        page5.grid_rowconfigure(2, weight=0)
        page5.grid_rowconfigure(3, weight=0)
        page5.grid_rowconfigure(4, weight=0)
        page5.grid_columnconfigure(0, weight=1)
        page5.grid_columnconfigure(1, weight=1)
        page5.grid_columnconfigure(2, weight=1)
        page5.grid_columnconfigure(3, weight=1)
        page5.grid_columnconfigure(4, weight=1)

    def create_page6(self):
        page6 = tk.Frame(self.notebook, background="white")
        self.notebook.add(page6, text="は行")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page6, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=4, padx=5, pady=5, sticky="nsew")

        page6.grid_rowconfigure(0, weight=0)
        page6.grid_rowconfigure(1, weight=0)
        page6.grid_rowconfigure(2, weight=0)
        page6.grid_rowconfigure(3, weight=0)
        page6.grid_rowconfigure(4, weight=0)
        page6.grid_columnconfigure(0, weight=1)
        page6.grid_columnconfigure(1, weight=1)
        page6.grid_columnconfigure(2, weight=1)
        page6.grid_columnconfigure(3, weight=1)
        page6.grid_columnconfigure(4, weight=1)

    def create_page7(self):
        page7 = tk.Frame(self.notebook, background="white")
        self.notebook.add(page7, text="ま行")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page7, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=4, padx=5, pady=5, sticky="nsew")

        page7.grid_rowconfigure(0, weight=0)
        page7.grid_rowconfigure(1, weight=0)
        page7.grid_rowconfigure(2, weight=0)
        page7.grid_rowconfigure(3, weight=0)
        page7.grid_rowconfigure(4, weight=0)
        page7.grid_columnconfigure(0, weight=1)
        page7.grid_columnconfigure(1, weight=1)
        page7.grid_columnconfigure(2, weight=1)
        page7.grid_columnconfigure(3, weight=1)
        page7.grid_columnconfigure(4, weight=1)

    def create_page8(self):
        page8 = tk.Frame(self.notebook, background="white")
        self.notebook.add(page8, text="や行")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page8, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=4, padx=5, pady=5, sticky="nsew")

        page8.grid_rowconfigure(0, weight=0)
        page8.grid_rowconfigure(1, weight=0)
        page8.grid_rowconfigure(2, weight=0)
        page8.grid_rowconfigure(3, weight=0)
        page8.grid_rowconfigure(4, weight=0)
        page8.grid_columnconfigure(0, weight=1)
        page8.grid_columnconfigure(1, weight=1)
        page8.grid_columnconfigure(2, weight=1)
        page8.grid_columnconfigure(3, weight=1)
        page8.grid_columnconfigure(4, weight=1)

    def create_page9(self):
        page9 = tk.Frame(self.notebook, background="white")
        self.notebook.add(page9, text="ら行")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page9, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=4, padx=5, pady=5, sticky="nsew")

        page9.grid_rowconfigure(0, weight=0)
        page9.grid_rowconfigure(1, weight=0)
        page9.grid_rowconfigure(2, weight=0)
        page9.grid_rowconfigure(3, weight=0)
        page9.grid_rowconfigure(4, weight=0)
        page9.grid_columnconfigure(0, weight=1)
        page9.grid_columnconfigure(1, weight=1)
        page9.grid_columnconfigure(2, weight=1)
        page9.grid_columnconfigure(3, weight=1)
        page9.grid_columnconfigure(4, weight=1)

    def create_page10(self):
        page10 = tk.Frame(self.notebook, background="white")
        self.notebook.add(page10, text="わ行")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=0, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=1, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=2, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=3, column=4, padx=5, pady=5, sticky="nsew")

        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=0, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=1, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=2, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=3, padx=5, pady=5, sticky="nsew")
        tk.Button(page10, text="先生", font=("Noto Sans JP", 20), width=10, height=3, command=lambda: self.play_sound("./system/sample.wav")).grid(row=4, column=4, padx=5, pady=5, sticky="nsew")

        page10.grid_rowconfigure(0, weight=0)
        page10.grid_rowconfigure(1, weight=0)
        page10.grid_rowconfigure(2, weight=0)
        page10.grid_rowconfigure(3, weight=0)
        page10.grid_rowconfigure(4, weight=0)
        page10.grid_columnconfigure(0, weight=1)
        page10.grid_columnconfigure(1, weight=1)
        page10.grid_columnconfigure(2, weight=1)
        page10.grid_columnconfigure(3, weight=1)
        page10.grid_columnconfigure(4, weight=1)